# This file was generated by ChatGPT

import numpy as np
import gensim


def get_word_embeddings(filename, model_path):
    print("inside function")
    # Load the pre-trained GloVe model from the zip file
    model = gensim.models.KeyedVectors.load_word2vec_format(model_path, binary=False)

    # Open the input file and read its contents
    with open(filename, "r") as f:
        contents = f.read()

    # Split the contents into blocks based on integer line followed by a blank line
    blocks = contents.split("\n\n")
    embeddings_list = []

    # Iterate over the blocks and extract the word embeddings for each one
    for block in blocks:
        # Tokenize the block into individual words
        words = block.split()
        # Create an empty array to store the embeddings for each word
        embeddings = np.zeros((len(words), model.vector_size))
        # Iterate over the words and get their embeddings
        for i, word in enumerate(words):
            if word in model:
                embeddings[i] = model[word]
        embeddings_list.append(embeddings)

    return embeddings_list
